/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MantenimientoUsuario.java
 *
 * Created on Oct 2, 2011, 3:57:16 PM
 */
package Seguridad.Usuario;

import BusinessEntity.PerfilBE;
import BusinessEntity.UsuarioBE;
import BusinessLogic.UsuarioBL;
import BusinessLogic.UsuarioContrasenaBL;
import DataAccess.PerfilDA;
import Util.Utilitario;
import java.util.Date;
import java.util.ArrayList;
import java.util.Calendar;

import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author DIEGO
 */
public class MantenimientoUsuario extends javax.swing.JFrame {

    /** Creates new form MantenimientoUsuario */
    private AdmUsuario objPadre;
    private String accion;
    
    public MantenimientoUsuario(AdmUsuario padre) {
        this.objPadre = padre;
        accion = "registrar";       
        initComponents();
        this.setLocationRelativeTo(null); 
        this.setTitle("+Flow - Registrar usuario"); 
//        this.txtIdUsuario.setEnabled(false);
        this.ckbActivo.setSelected(true);
        this.llenarCombo();
        this.setVisible(true);
    }

    MantenimientoUsuario(AdmUsuario padre, UsuarioBE usuario) {
        this.objPadre = padre;
        accion = "modificar";        
        initComponents();
        this.setLocationRelativeTo(null);
        this.ckbActivo.setEnabled(true);
        this.setTitle("+Flow - Editar Usuario");
//        this.txtIdUsuario.setEnabled(false);
        this.llenarCombo();
        this.txtIdUsuario.setText(usuario.getIdUsuario());
        this.txtNombre.setText(usuario.getNombre());
        this.txtPaterno.setText(usuario.getPaterno());
        this.txtMaterno.setText(usuario.getMaterno());
        String idEstadoUsuario=usuario.getEstadoUsuario().getIdEstadoUsuario().trim();
        if (idEstadoUsuario.equals("1"))
        {
            this.ckbActivo.setSelected(true);
         
        }else{
            this.ckbActivo.setSelected(false);
        }
        this.cmbPerfil.setSelectedIndex(Integer.parseInt(usuario.getPerfil().getIdPerfil().trim())); 
        this.setVisible(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtIdUsuario = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        cmbPerfil = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtPaterno = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtMaterno = new javax.swing.JTextField();
        ckbActivo = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("+Flow - Registrar  usuario");

        txtIdUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIdUsuarioKeyTyped(evt);
            }
        });

        jLabel1.setText("Usuario :");

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        jLabel3.setText("Perfil*:");

        jLabel2.setText("Apellido Materno*:");

        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });

        jLabel4.setText("Apellido Paterno*:");

        txtPaterno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPaternoKeyTyped(evt);
            }
        });

        jLabel5.setText("Nombres*:");

        txtMaterno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMaternoKeyTyped(evt);
            }
        });

        ckbActivo.setText("Activo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(ckbActivo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cmbPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE))
                            .addComponent(txtMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                            .addComponent(txtIdUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(btnGuardar)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancelar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(75, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addComponent(ckbActivo)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnGuardar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
// TODO add your handling code here:
    if ((txtIdUsuario.getText().length())==0) {
            JOptionPane.showMessageDialog(null, "Falta indicar usuario.", "Error", 0);
            return;
    }
    
    if ((txtNombre.getText().length())==0) {
            JOptionPane.showMessageDialog(null, "Falta indicar nombre.", "Error", 0);
            return;
    }
    if ((txtPaterno.getText().length())==0) {
            JOptionPane.showMessageDialog(null, "Falta indicar Apellido Paterno.", "Error", 0);
            return;
    }
    if ((txtMaterno.getText().length())==0) {
            JOptionPane.showMessageDialog(null, "Falta indicar Apellido Materno.", "Error", 0);
            return;
    }
    if ((txtNombre.getText().length())==0) {
            JOptionPane.showMessageDialog(null, "Falta indicar nombre.", "Error", 0);
            return;
    }
    
    if (((cmbPerfil.getSelectedIndex()==0)|| (cmbPerfil.getSelectedIndex()==-1))) {
            JOptionPane.showMessageDialog(null, "Falta indicar Perfil.", "Error", 0);
            return;
    }
        
    
    
    UsuarioBL objUsuarioBL = new UsuarioBL();    
    try {
           
        Date fechaHoy = new Date();
        if(this.accion.equals("registrar")){                               
                    String estado;
                    if(this.ckbActivo.isSelected()){
                        estado = "1";
                    }else estado = "0";
                    //revisar porque esto solo funciona para perfiles menores a 10
                    PerfilDA objPerfilDA = new PerfilDA();
                    
                    String nombrePerfil=((String)(this.cmbPerfil.getSelectedItem())).trim();
                    
                    PerfilBE objPerfilBE=objPerfilDA.queryByNombre(nombrePerfil);
                    
                    UsuarioBE usuario = objUsuarioBL.queryByIdUsuario(txtIdUsuario.getText());
                    
                    if (usuario == null){

                        String ok= objUsuarioBL.insertar(this.txtIdUsuario.getText(),this.txtNombre.getText(), this.txtPaterno.getText(),this.txtMaterno.getText(),objPerfilBE.getIdPerfil(),estado,3);
                        if (ok.equals("1")){
                            
                            usuario = objUsuarioBL.getUsuario();
                            UsuarioContrasenaBL objUsuarioContrasenaBL=new UsuarioContrasenaBL();

                          //  Date fechaFin=(java.sql.Date)fechaMas((java.sql.Date) fechaHoy,30);

                            String ind=objUsuarioContrasenaBL.insertarUsuarioContrasena(usuario.getIdUsuario(),usuario.getIdUsuario(),fechaHoy,fechaHoy);
                            if (ind.equals("1")){
                                JOptionPane.showMessageDialog(null, "Su contraseña es "+usuario.getIdUsuario(), "Mensaje", 0);
                            }
                            this.objPadre.recargaruno(usuario);
                            this.dispose();
                        } else {
                                JOptionPane.showMessageDialog(null, "Ocurrió un error inesperado.", "Error", 0);
                                return;
                            }
                        this.dispose();
                    }else{
                        JOptionPane.showMessageDialog(null, "Usuario ya exsiste.", "Error", 0);
                        return;
                    }

                 
        }
        if(this.accion.equals("modificar")){
                     UsuarioBE usuario = null;
                     String estado;
                    if(this.ckbActivo.isSelected()){
                        estado = "1";
                    }else estado = "0";   
                    PerfilDA objPerfilDA = new PerfilDA();
                    PerfilBE objPerfilBE=objPerfilDA.queryByNombre((String)(this.cmbPerfil.getSelectedItem()));

                    
                    
                    usuario = objUsuarioBL.setUsuario(this.txtIdUsuario.getText(),this.txtNombre.getText(), this.txtPaterno.getText(),this.txtMaterno.getText(),objPerfilBE.getIdPerfil(),estado,3);
                    boolean ok= objUsuarioBL.modificar(usuario);
                    int fila;
                    fila = this.objPadre.getDgvUsuario().getSelectedRow();
                    this.objPadre.getDgvUsuario().removeRowSelectionInterval(fila, fila);
                    this.objPadre.getDgvUsuario().setValueAt(usuario.getIdUsuario(), fila, 0);
                    this.objPadre.getDgvUsuario().setValueAt(usuario.getNombre(), fila, 1);
                    this.objPadre.getDgvUsuario().setValueAt(usuario.getPaterno(), fila, 2);
                    this.objPadre.getDgvUsuario().setValueAt(usuario.getMaterno(), fila, 3);
                    this.objPadre.getDgvUsuario().setValueAt(usuario.getPerfil().getDescripcion(), fila, 4);
                    this.objPadre.getDgvUsuario().setValueAt(usuario.getEstadoUsuario().getDescripcion(), fila, 5);
                    this.dispose();
                 }
      } catch (Exception ex) {
                Logger.getLogger(MantenimientoUsuario.class.getName()).log(Level.SEVERE, null, ex);
      }



    
}//GEN-LAST:event_btnGuardarActionPerformed

public java.sql.Date fechaMas(java.sql.Date fch, int dias){
     Calendar cal = new GregorianCalendar();
     cal.setTimeInMillis(fch.getTime());
     cal.add(Calendar.DATE, dias);
     return (java.sql.Date) new Date(cal.getTimeInMillis());

   }

private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
// TODO add your handling code here:
     this.dispose();
}//GEN-LAST:event_btnCancelarActionPerformed

private void txtIdUsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdUsuarioKeyTyped
// TODO add your handling code here:
       char c = (char)evt.getKeyChar();
       if (!Utilitario.validarCadenaAlfaNumerica(evt.getKeyChar()) || (Character.isISOControl(c)))
            evt.consume();
       if ((this.txtIdUsuario.getText().length() + 1) > 11) {
            evt.consume();
        }

}//GEN-LAST:event_txtIdUsuarioKeyTyped

private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
// TODO add your handling code here:
       char c = (char)evt.getKeyChar();
       if (!Utilitario.validarCadenaAlfabetica(evt.getKeyChar()) || (Character.isISOControl(c)))
            evt.consume();
       if ((this.txtNombre.getText().length() + 1) > 30) {
            evt.consume();
        }
}//GEN-LAST:event_txtNombreKeyTyped

private void txtPaternoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPaternoKeyTyped
// TODO add your handling code here:
       char c = (char)evt.getKeyChar();
       if (!Utilitario.validarCadenaAlfabetica(evt.getKeyChar()) || (Character.isISOControl(c)))
            evt.consume();
       if ((this.txtPaterno.getText().length() + 1) > 30) {
            evt.consume();
        }
}//GEN-LAST:event_txtPaternoKeyTyped

private void txtMaternoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMaternoKeyTyped
// TODO add your handling code here:
    
       char c = (char)evt.getKeyChar();
       if (!Utilitario.validarCadenaAlfabetica(evt.getKeyChar()) || (Character.isISOControl(c)))
            evt.consume();
       if ((this.txtMaterno.getText().length() + 1) > 30) {
            evt.consume();
        }
       
}//GEN-LAST:event_txtMaternoKeyTyped

    /**
     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(MantenimientoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(MantenimientoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(MantenimientoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(MantenimientoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//
//            public void run() {
//                new MantenimientoUsuario().setVisible(true);
//            }
//        });
//    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JCheckBox ckbActivo;
    private javax.swing.JComboBox cmbPerfil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtIdUsuario;
    private javax.swing.JTextField txtMaterno;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPaterno;
    // End of variables declaration//GEN-END:variables

        private void llenarCombo() {
            
        PerfilDA objPerfilDA =new PerfilDA();
        

       try { ArrayList<PerfilBE> arrPerfil= objPerfilDA.queryAll();
        cmbPerfil.addItem("Seleccione");
        for (PerfilBE perfil : arrPerfil){
            cmbPerfil.addItem(perfil.getDescripcion());
        }
        } catch (Exception ex) {
            Logger.getLogger(MantenimientoUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }
//        index = OGGestorTipoDocIdentidad.indexTipoDocIdentidad(arrTipoDocIdentidad,objCliente.getObjTipoDocIdentidad().getStrIdTipoDocIdentidad());
//        jcmbTipoDocumento.setSelectedIndex(index+1);


    }


}
