/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MantenimientoCliente.java
 *
 * Created on Oct 2, 2011, 3:34:26 PM
 */
package Mantenimientos.Cliente;
import BusinessEntity.CIUUBE;
import BusinessEntity.EntidadBE;
import BusinessLogic.EntidadBL;
import java.util.ArrayList;
import DataAccess.CIUUDA;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author DIEGO
 */
public class MantenimientoCliente extends javax.swing.JFrame {
 int tipoVentana;
    /** Creates new form MantenimientoCliente 
    public MantenimientoCliente() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.llenarCombo();
        
    }
*/
     public MantenimientoCliente(int i, String codigoCliente) throws Exception{
         tipoVentana=i;
         
         initComponents();
         this.jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Contacto"));
         this.setLocationRelativeTo(null);
         this.buttonGroup1.add(this.rdbEmpresa);
         this.buttonGroup1.add(this.rdbPersona);
         this.llenarCombo();

         if (i==0) {
            this.setTitle("+Flow - Registrar cliente");
                 
        } else {
            this.setTitle("+Flow - Editar cliente");

            EntidadBE cliente = new EntidadBE();
            EntidadBL objEntidadBL = new EntidadBL();
            cliente =objEntidadBL.getCliente(codigoCliente);

            txtCodigo.setText(cliente.getIdEntidad());
            txtDoc.setText(cliente.getNroDocumento());
            txtDireccion.setText(cliente.getDireccion());
            txtTelefono.setText(cliente.getTelefono());
            txtEmail.setText(cliente.getEmail());
            txtNombreContacto.setText(cliente.getNombreContacto());
            txtDNIContacto.setText(cliente.getDniContacto());
            txtTelfContacto.setText(cliente.getTelefonoContacto());
            //txtIdTipoPersona.setText(cliente.      ());
            txtRazonSocial.setText(cliente.getRazonSocial());
            txtPaginaWeb.setText(cliente.getPaginaWeb());
            //txtIdTipoEntidad.setText(cliente.getIdEntidad());

            if (cliente.getIndActivo()=="1"){
                cbxActivo.setSelected(true);
            } else{
                cbxActivo.setSelected(false);
            }

            //txtIdCIUU.setText(cliente.getIdEntidad());

            this.setVisible(true) ;
        
        }
            
                
         
       
    }
     
     
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel10 = new javax.swing.JLabel();
        txtRazonSocial = new javax.swing.JTextField();
        txtPaginaWeb = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txtNombreContacto = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtDNIContacto = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtTelfContacto = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        rdbEmpresa = new javax.swing.JRadioButton();
        rdbPersona = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        cmbCIUU = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtDoc = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        cbxActivo = new javax.swing.JCheckBox();
        btnCancelar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("+Flow - Registrar cliente");

        jLabel10.setText("E-mail:");

        txtRazonSocial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRazonSocialActionPerformed(evt);
            }
        });
        txtRazonSocial.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRazonSocialKeyTyped(evt);
            }
        });

        txtPaginaWeb.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPaginaWebKeyTyped(evt);
            }
        });

        txtTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefonoActionPerformed(evt);
            }
        });
        txtTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelefonoKeyTyped(evt);
            }
        });

        jLabel9.setText("Nombre:");

        txtNombreContacto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreContactoKeyTyped(evt);
            }
        });

        jLabel8.setText("DNI:");

        txtDNIContacto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDNIContactoKeyTyped(evt);
            }
        });

        jLabel11.setText("Telf:");

        txtTelfContacto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelfContactoKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(txtDNIContacto, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                        .addComponent(jLabel11)
                        .addGap(28, 28, 28)
                        .addComponent(txtTelfContacto, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtNombreContacto, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtNombreContacto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtDNIContacto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelfContacto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jLabel2.setText("Documento*:");

        rdbEmpresa.setText("Empresa");

        rdbPersona.setText("Persona");

        jLabel1.setText("Código:");

        txtDireccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDireccionKeyTyped(evt);
            }
        });

        txtEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEmailKeyTyped(evt);
            }
        });

        jLabel5.setText("Teléfono:");

        jLabel3.setText("Razón Social*:");

        txtDoc.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDocFocusLost(evt);
            }
        });
        txtDoc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDocKeyTyped(evt);
            }
        });

        jLabel4.setText("Dirección:");

        jLabel7.setText("CIUU:");

        jLabel6.setText("Página Web:");

        txtCodigo.setEnabled(false);

        cbxActivo.setSelected(true);
        cbxActivo.setText("Activo");

        btnCancelar.setText("Cancelar");
        btnCancelar.setMaximumSize(new java.awt.Dimension(75, 30));
        btnCancelar.setMinimumSize(new java.awt.Dimension(75, 30));
        btnCancelar.setPreferredSize(new java.awt.Dimension(100, 23));
        btnCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnCancelarMousePressed(evt);
            }
        });

        btnGuardar.setText("Guardar");
        btnGuardar.setMaximumSize(new java.awt.Dimension(75, 23));
        btnGuardar.setMinimumSize(new java.awt.Dimension(75, 23));
        btnGuardar.setPreferredSize(new java.awt.Dimension(100, 23));
        btnGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnGuardarMousePressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(cbxActivo)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 376, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel7)
                                .addComponent(jLabel4)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel10)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel3))
                                    .addGap(5, 5, 5)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(txtRazonSocial, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE)
                                        .addComponent(cmbCIUU, javax.swing.GroupLayout.Alignment.LEADING, 0, 342, Short.MAX_VALUE)
                                        .addComponent(txtDireccion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE)
                                        .addComponent(txtTelefono, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE)
                                        .addComponent(txtPaginaWeb, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE)
                                        .addComponent(txtEmail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(rdbEmpresa)
                                    .addGap(18, 18, 18)
                                    .addComponent(rdbPersona)
                                    .addGap(33, 33, 33)
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtDoc, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(37, 37, 37)
                                .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(25, 25, 25))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(87, 87, 87)))
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdbPersona)
                    .addComponent(txtDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rdbEmpresa)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtRazonSocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cmbCIUU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtPaginaWeb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbxActivo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMousePressed
        this.dispose();    // TODO add your handling code here:
}//GEN-LAST:event_btnCancelarMousePressed

    private void btnGuardarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMousePressed

        String tipoPersona = new String();
        if ((txtDoc.getText().length())==8) {tipoPersona="N";} else if ((txtDoc.getText().length())==11) {tipoPersona="J";} else {JOptionPane.showMessageDialog(null, "DNI/RUC incorrecto.", "Error", 0);
        return;
        }

        if ((txtRazonSocial.getText().length())==0) {
            JOptionPane.showMessageDialog(null, "Falta indicar razón social.", "Error", 0);
            return;
        }

        if ((cmbCIUU.getSelectedIndex()==0) && txtDoc.getText().length()!=8) {
            JOptionPane.showMessageDialog(null, "Falta indicar CIUU.", "Error", 0);
            return;
        }

        if ((txtDireccion.getText().length())==0) {
            JOptionPane.showMessageDialog(null, "Falta indicar dirección.", "Error", 0);
            return;
        }

        if ((txtTelefono.getText().length())==0) {
            JOptionPane.showMessageDialog(null, "Falta indicar teléfono del cliente.", "Error", 0);
            return;
        }

        if ((txtPaginaWeb.getText().length()==0)&& txtDoc.getText().length()!=8) {
            JOptionPane.showMessageDialog(null, "Falta indicar página web.", "Error", 0);
            return;
        }

        if ((txtEmail.getText().length())==0) {
            JOptionPane.showMessageDialog(null, "Falta indicar email.", "Error", 0);
            return;
        }

        if ((txtNombreContacto.getText().length()==0)&& txtDoc.getText().length()!=8) {
            JOptionPane.showMessageDialog(null, "Falta indicar nombre del contacto.", "Error", 0);
            return;
        }

        if ((txtDNIContacto.getText().length()==0)&& txtDoc.getText().length()!=8) {
            JOptionPane.showMessageDialog(null, "Falta indicar DNI del contacto.", "Error", 0);
            return;
        }

        if ((txtTelfContacto.getText().length()==0)&& txtDoc.getText().length()!=8) {
            JOptionPane.showMessageDialog(null, "Falta indicar teléfono del contacto.", "Error", 0);
            return;
        }

        String indActivo = new String();
        if (cbxActivo.isSelected()) {indActivo="1";} else {indActivo="0";}



        EntidadBL entidadBL = new EntidadBL();
        try {
            if (this.tipoVentana==0){entidadBL.insertar("C-"+txtDoc.getText(),txtDoc.getText(),txtDireccion.getText(),
                    txtTelefono.getText(),txtEmail.getText(),txtNombreContacto.getText(),
                    txtDNIContacto.getText(), txtTelfContacto.getText(),
                    txtRazonSocial.getText(), txtPaginaWeb.getText(),  indActivo,
                    cmbCIUU.getSelectedItem().toString().substring(0,1) );} else {
                entidadBL.modificar("C-"+txtDoc.getText(),txtCodigo.getText(),txtDoc.getText(),txtDireccion.getText(),
                        txtTelefono.getText(),txtEmail.getText(),txtNombreContacto.getText(),
                        txtDNIContacto.getText(), txtTelfContacto.getText(),
                        txtRazonSocial.getText(), txtPaginaWeb.getText(),  indActivo,
                        cmbCIUU.getSelectedItem().toString().substring(0,1) );

                    }



        } catch (Exception ex) {
            Logger.getLogger(MantenimientoCliente.class.getName()).log(Level.SEVERE, null, ex);
        }

        this.hide();
        // TODO add your handling code here:
}//GEN-LAST:event_btnGuardarMousePressed

    private void txtRazonSocialKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRazonSocialKeyTyped
        if ((this.txtRazonSocial.getText().length() + 1) > 60) {
            evt.consume();
        }
        // TODO add your handling code here:
}//GEN-LAST:event_txtRazonSocialKeyTyped

    private void txtRazonSocialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRazonSocialActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_txtRazonSocialActionPerformed

    private void txtPaginaWebKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPaginaWebKeyTyped
        if ((this.txtPaginaWeb.getText().length() + 1) > 30) {
            evt.consume();}

        // TODO add your handling code here:
}//GEN-LAST:event_txtPaginaWebKeyTyped

    private void txtDocKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDocKeyTyped
        char c = (char)evt.getKeyChar();
        if ((c >= '0' && c <= '9') || (Character.isISOControl(c))) {
            // keep digit
        } else {
            evt.consume();
        }
        if ((this.txtDoc.getText().length() + 1) > 11) {
            evt.consume();
        }
}//GEN-LAST:event_txtDocKeyTyped

    private void txtDocFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDocFocusLost
        if ((this.txtDoc.getText().length() ) == 8){
            this.cmbCIUU.setEnabled(false);
            this.txtPaginaWeb.setEnabled(false);
            this.txtNombreContacto.setEnabled(false);
            this.txtDNIContacto.setEnabled(false);
            this.txtTelfContacto.setEnabled(false);
        } else{
            this.cmbCIUU.setEnabled(true);
            this.txtPaginaWeb.setEnabled(true);
            this.txtNombreContacto.setEnabled(true);
            this.txtDNIContacto.setEnabled(true);
            this.txtTelfContacto.setEnabled(true);
        }


        // TODO add your handling code here:
}//GEN-LAST:event_txtDocFocusLost

    private void txtEmailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailKeyTyped
        if ((this.txtEmail.getText().length() + 1) > 30) {
            evt.consume();}// TODO add your handling code here:
}//GEN-LAST:event_txtEmailKeyTyped

    private void txtDireccionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDireccionKeyTyped
        if ((this.txtDireccion.getText().length() + 1) > 60) { evt.consume();        }
        // TODO add your handling code here:
}//GEN-LAST:event_txtDireccionKeyTyped

    private void txtTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoKeyTyped
        char c = (char)evt.getKeyChar();
        if((c>='0' && c<='9') || (Character.isISOControl(c))){
        } else { evt.consume(); }

        if ((this.txtTelefono.getText().length() + 1) > 12) {
            evt.consume();
        }// TODO add your handling code here:
}//GEN-LAST:event_txtTelefonoKeyTyped

    private void txtTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_txtTelefonoActionPerformed

    private void txtTelfContactoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelfContactoKeyTyped
        char c = (char)evt.getKeyChar();
        if((c>='0' && c<='9') || (Character.isISOControl(c))){
        } else { evt.consume(); }
        if ((this.txtTelfContacto.getText().length() + 1) > 12) {
            evt.consume();}// TODO add your handling code here:
}//GEN-LAST:event_txtTelfContactoKeyTyped

    private void txtDNIContactoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDNIContactoKeyTyped
        char c = (char)evt.getKeyChar();
        if((c>='0' && c<='9') || (Character.isISOControl(c))){
        } else { evt.consume(); }
        if ((this.txtDNIContacto.getText().length() + 1) > 8) {
            evt.consume();}// TODO add your handling code here:
}//GEN-LAST:event_txtDNIContactoKeyTyped

    private void txtNombreContactoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreContactoKeyTyped
        if ((this.txtNombreContacto.getText().length() + 1) > 30) {
            evt.consume();}// TODO add your handling code here:
}//GEN-LAST:event_txtNombreContactoKeyTyped
    
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(MantenimientoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(MantenimientoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(MantenimientoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(MantenimientoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//
//            public void run() {
//                new MantenimientoCliente(tipoVentana, "").setVisible(true);
//            }
//        });
//    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox cbxActivo;
    private javax.swing.JComboBox cmbCIUU;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton rdbEmpresa;
    private javax.swing.JRadioButton rdbPersona;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtDNIContacto;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtDoc;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNombreContacto;
    private javax.swing.JTextField txtPaginaWeb;
    private javax.swing.JTextField txtRazonSocial;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtTelfContacto;
    // End of variables declaration//GEN-END:variables

    private void llenarCombo() {

       try { ArrayList<CIUUBE> arrCIUU = DataAccess.CIUUDA.queryAllCIUU();
        cmbCIUU.addItem("Seleccione");
        for (CIUUBE CIUU : arrCIUU){
            cmbCIUU.addItem((CIUU.getIdCIUU() + " - " + CIUU.getDescripcion()));
        }
} catch (Exception ex) {
            Logger.getLogger(MantenimientoCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
//        index = OGGestorTipoDocIdentidad.indexTipoDocIdentidad(arrTipoDocIdentidad,objCliente.getObjTipoDocIdentidad().getStrIdTipoDocIdentidad());
//        jcmbTipoDocumento.setSelectedIndex(index+1);


    }
}
