/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MenuPrincipal.java
 *
 * Created on Oct 2, 2011, 5:10:59 PM
 */
package masflow;

import BusinessEntity.UsuarioSistema;
import CargaMasiva.CargaMasiva;
import Reportes.LogUsuario;
import Seguridad.ConstantesSeguridad;
import Seguridad.Login;

/**
 *
 * @author DIEGO
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /** Creates new form MenuPrincipal */
    public MenuPrincipal() {
        
        initComponents();

        

        int nc1=this.jLayeredPaneMantenimientos.getComponentCount();
        for(int i=0;i<nc1;i++){
            if(!UsuarioSistema.PermisoParaAplicacion(this.jLayeredPaneMantenimientos.getComponent(i).getName())){
                this.jLayeredPaneMantenimientos.getComponent(i).setEnabled(false);
            }
        }
        int nc2=this.jLayeredPaneProcesos.getComponentCount();
        for(int i=0;i<nc2;i++){
            if(!UsuarioSistema.PermisoParaAplicacion(this.jLayeredPaneProcesos.getComponent(i).getName())){
                this.jLayeredPaneProcesos.getComponent(i).setEnabled(false);
            }
        }
        int nc3=this.jLayeredPaneReportes.getComponentCount();
        for(int i=0;i<nc3;i++){
            if(!UsuarioSistema.PermisoParaAplicacion(this.jLayeredPaneReportes.getComponent(i).getName())){
                this.jLayeredPaneReportes.getComponent(i).setEnabled(false);
            }
        }
        int nc4=this.jLayeredPaneSeguridad.getComponentCount();
        for(int i=0;i<nc4;i++){
            if(!UsuarioSistema.PermisoParaAplicacion(this.jLayeredPaneSeguridad.getComponent(i).getName())){
                this.jLayeredPaneSeguridad.getComponent(i).setEnabled(false);
            }
        }


        
        this.setLocationRelativeTo(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLayeredPaneMantenimientos = new javax.swing.JLayeredPane();
        jLblFamilia = new javax.swing.JLabel();
        jLblClientes = new javax.swing.JLabel();
        jLblAlmacenes = new javax.swing.JLabel();
        jLblUbicaciones = new javax.swing.JLabel();
        jLblProveedores = new javax.swing.JLabel();
        jLblProductos = new javax.swing.JLabel();
        jLblZonas = new javax.swing.JLabel();
        jLblRacks = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLayeredPaneProcesos = new javax.swing.JLayeredPane();
        jLblIngresarProductos = new javax.swing.JLabel();
        jLblDespacharProductos = new javax.swing.JLabel();
        jLblMovimientosInternos = new javax.swing.JLabel();
        jLayeredPaneReportes = new javax.swing.JLayeredPane();
        jLblReporteStock = new javax.swing.JLabel();
        jLblKardek = new javax.swing.JLabel();
        jLblTrazabilidadPallet = new javax.swing.JLabel();
        jLblLogAuditoria = new javax.swing.JLabel();
        jLblLogUsuario = new javax.swing.JLabel();
        jLblGuiaDeRemision = new javax.swing.JLabel();
        jLblOrdenDeEntrega = new javax.swing.JLabel();
        jLayeredPaneSeguridad = new javax.swing.JLayeredPane();
        jLblPerfiles = new javax.swing.JLabel();
        jLblCambioContrasena = new javax.swing.JLabel();
        jLblUsuarios = new javax.swing.JLabel();
        jLayeredPaneLogo = new javax.swing.JLayeredPane();
        jLabel45 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("+Flow - Menú Principal");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFocusable(false);
        setFocusableWindowState(false);
        setResizable(false);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Mantenimientos.png"))); // NOI18N
        jLabel5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel5MousePressed(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/procesos.png"))); // NOI18N
        jLabel6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/reportes.png"))); // NOI18N
        jLabel7.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/seguridad.png"))); // NOI18N
        jLabel8.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setText("Mantenimientos");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel2.setForeground(new java.awt.Color(0, 0, 102));
        jLabel2.setText("Procesos");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel3.setForeground(new java.awt.Color(0, 0, 102));
        jLabel3.setText("Seguridad");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel4.setForeground(new java.awt.Color(0, 0, 102));
        jLabel4.setText("Reportes");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLblFamilia.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLblFamilia.setForeground(new java.awt.Color(0, 0, 102));
        jLblFamilia.setText("Familias");
        jLblFamilia.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLblFamilia.setName("000005"); // NOI18N
        jLblFamilia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLblFamiliaMousePressed(evt);
            }
        });
        jLblFamilia.setBounds(50, 130, 70, 17);
        jLayeredPaneMantenimientos.add(jLblFamilia, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLblClientes.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLblClientes.setForeground(new java.awt.Color(0, 0, 102));
        jLblClientes.setText("Clientes");
        jLblClientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLblClientes.setName("000008"); // NOI18N
        jLblClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLblClientesMousePressed(evt);
            }
        });
        jLblClientes.setBounds(50, 220, 70, 17);
        jLayeredPaneMantenimientos.add(jLblClientes, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLblAlmacenes.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLblAlmacenes.setForeground(new java.awt.Color(0, 0, 102));
        jLblAlmacenes.setText("Almacenes");
        jLblAlmacenes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLblAlmacenes.setName("000001"); // NOI18N
        jLblAlmacenes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLblAlmacenesMousePressed(evt);
            }
        });
        jLblAlmacenes.setBounds(50, 10, 90, 17);
        jLayeredPaneMantenimientos.add(jLblAlmacenes, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLblUbicaciones.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLblUbicaciones.setForeground(new java.awt.Color(0, 0, 102));
        jLblUbicaciones.setText("Ubicaciones");
        jLblUbicaciones.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLblUbicaciones.setName("000004"); // NOI18N
        jLblUbicaciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLblUbicacionesMousePressed(evt);
            }
        });
        jLblUbicaciones.setBounds(50, 100, 100, 17);
        jLayeredPaneMantenimientos.add(jLblUbicaciones, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLblProveedores.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLblProveedores.setForeground(new java.awt.Color(0, 0, 102));
        jLblProveedores.setText("Proveedores");
        jLblProveedores.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLblProveedores.setName("000007"); // NOI18N
        jLblProveedores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLblProveedoresMousePressed(evt);
            }
        });
        jLblProveedores.setBounds(50, 190, 100, 17);
        jLayeredPaneMantenimientos.add(jLblProveedores, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLblProductos.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLblProductos.setForeground(new java.awt.Color(0, 0, 102));
        jLblProductos.setText("Productos");
        jLblProductos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLblProductos.setName("000006"); // NOI18N
        jLblProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLblProductosMousePressed(evt);
            }
        });
        jLblProductos.setBounds(50, 160, 90, 17);
        jLayeredPaneMantenimientos.add(jLblProductos, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLblZonas.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLblZonas.setForeground(new java.awt.Color(0, 0, 102));
        jLblZonas.setText("Zonas");
        jLblZonas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLblZonas.setName("000002"); // NOI18N
        jLblZonas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLblZonasMousePressed(evt);
            }
        });
        jLblZonas.setBounds(50, 40, 60, 17);
        jLayeredPaneMantenimientos.add(jLblZonas, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLblRacks.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLblRacks.setForeground(new java.awt.Color(0, 0, 102));
        jLblRacks.setText("Racks");
        jLblRacks.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLblRacks.setName("000003"); // NOI18N
        jLblRacks.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLblRacksMousePressed(evt);
            }
        });
        jLblRacks.setBounds(50, 70, 60, 17);
        jLayeredPaneMantenimientos.add(jLblRacks, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/exit.png"))); // NOI18N
        jLabel10.setToolTipText("Salir");
        jLabel10.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel10MousePressed(evt);
            }
        });
        jLabel10.setBounds(20, 300, 54, 50);
        jLayeredPaneMantenimientos.add(jLabel10, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLblIngresarProductos.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLblIngresarProductos.setForeground(new java.awt.Color(0, 0, 102));
        jLblIngresarProductos.setText("Ingresar Productos");
        jLblIngresarProductos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLblIngresarProductos.setName("000009"); // NOI18N
        jLblIngresarProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLblIngresarProductosMousePressed(evt);
            }
        });
        jLblIngresarProductos.setBounds(30, 10, 150, 17);
        jLayeredPaneProcesos.add(jLblIngresarProductos, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLblDespacharProductos.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLblDespacharProductos.setForeground(new java.awt.Color(0, 0, 102));
        jLblDespacharProductos.setText("Despachar Productos");
        jLblDespacharProductos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLblDespacharProductos.setName("000010"); // NOI18N
        jLblDespacharProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLblDespacharProductosMousePressed(evt);
            }
        });
        jLblDespacharProductos.setBounds(30, 40, 160, 17);
        jLayeredPaneProcesos.add(jLblDespacharProductos, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLblMovimientosInternos.setFont(new java.awt.Font("Droid Sans", 0, 14));
        jLblMovimientosInternos.setForeground(new java.awt.Color(0, 0, 100));
        jLblMovimientosInternos.setText("Movimientos Internos");
        jLblMovimientosInternos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLblMovimientosInternos.setName("000011"); // NOI18N
        jLblMovimientosInternos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLblMovimientosInternosMouseClicked(evt);
            }
        });
        jLblMovimientosInternos.setBounds(30, 70, 160, 17);
        jLayeredPaneProcesos.add(jLblMovimientosInternos, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLblReporteStock.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLblReporteStock.setForeground(new java.awt.Color(0, 0, 102));
        jLblReporteStock.setText("Stock de Productos");
        jLblReporteStock.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLblReporteStock.setName("000012"); // NOI18N
        jLblReporteStock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLblReporteStockMousePressed(evt);
            }
        });
        jLblReporteStock.setBounds(30, 10, 140, 17);
        jLayeredPaneReportes.add(jLblReporteStock, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLblKardek.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLblKardek.setForeground(new java.awt.Color(0, 0, 102));
        jLblKardek.setText("Kárdex");
        jLblKardek.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLblKardek.setName("000013"); // NOI18N
        jLblKardek.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLblKardekMousePressed(evt);
            }
        });
        jLblKardek.setBounds(30, 40, 70, 17);
        jLayeredPaneReportes.add(jLblKardek, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLblTrazabilidadPallet.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLblTrazabilidadPallet.setForeground(new java.awt.Color(0, 0, 102));
        jLblTrazabilidadPallet.setText("Trazabilidad de Pallet");
        jLblTrazabilidadPallet.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLblTrazabilidadPallet.setName("000014"); // NOI18N
        jLblTrazabilidadPallet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLblTrazabilidadPalletMousePressed(evt);
            }
        });
        jLblTrazabilidadPallet.setBounds(30, 70, 150, 17);
        jLayeredPaneReportes.add(jLblTrazabilidadPallet, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLblLogAuditoria.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLblLogAuditoria.setForeground(new java.awt.Color(0, 0, 102));
        jLblLogAuditoria.setText("Log de Auditoría");
        jLblLogAuditoria.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLblLogAuditoria.setName("000015"); // NOI18N
        jLblLogAuditoria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLblLogAuditoriaMousePressed(evt);
            }
        });
        jLblLogAuditoria.setBounds(30, 100, 130, 17);
        jLayeredPaneReportes.add(jLblLogAuditoria, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLblLogUsuario.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLblLogUsuario.setForeground(new java.awt.Color(0, 0, 102));
        jLblLogUsuario.setText("Log de Usuario");
        jLblLogUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLblLogUsuario.setName("000016"); // NOI18N
        jLblLogUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLblLogUsuarioMousePressed(evt);
            }
        });
        jLblLogUsuario.setBounds(30, 130, 120, 17);
        jLayeredPaneReportes.add(jLblLogUsuario, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLblGuiaDeRemision.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLblGuiaDeRemision.setForeground(new java.awt.Color(0, 0, 102));
        jLblGuiaDeRemision.setText("Guía de Remisión");
        jLblGuiaDeRemision.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLblGuiaDeRemision.setName("000016"); // NOI18N
        jLblGuiaDeRemision.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLblGuiaDeRemisionMousePressed(evt);
            }
        });
        jLblGuiaDeRemision.setBounds(30, 190, 130, 17);
        jLayeredPaneReportes.add(jLblGuiaDeRemision, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLblOrdenDeEntrega.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLblOrdenDeEntrega.setForeground(new java.awt.Color(0, 0, 102));
        jLblOrdenDeEntrega.setText("Orden de Entrega");
        jLblOrdenDeEntrega.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLblOrdenDeEntrega.setName("000016"); // NOI18N
        jLblOrdenDeEntrega.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLblOrdenDeEntregaMousePressed(evt);
            }
        });
        jLblOrdenDeEntrega.setBounds(30, 160, 140, 17);
        jLayeredPaneReportes.add(jLblOrdenDeEntrega, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLblPerfiles.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLblPerfiles.setForeground(new java.awt.Color(0, 0, 102));
        jLblPerfiles.setText("Perfiles");
        jLblPerfiles.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLblPerfiles.setName("000017"); // NOI18N
        jLblPerfiles.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLblPerfilesMousePressed(evt);
            }
        });
        jLblPerfiles.setBounds(20, 10, 70, 17);
        jLayeredPaneSeguridad.add(jLblPerfiles, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLblCambioContrasena.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLblCambioContrasena.setForeground(new java.awt.Color(0, 0, 102));
        jLblCambioContrasena.setText("Cambio contraseña");
        jLblCambioContrasena.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLblCambioContrasena.setName("000019"); // NOI18N
        jLblCambioContrasena.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLblCambioContrasenaMousePressed(evt);
            }
        });
        jLblCambioContrasena.setBounds(20, 70, 150, 20);
        jLayeredPaneSeguridad.add(jLblCambioContrasena, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLblUsuarios.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLblUsuarios.setForeground(new java.awt.Color(0, 0, 102));
        jLblUsuarios.setText("Usuarios");
        jLblUsuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLblUsuarios.setName("000018"); // NOI18N
        jLblUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLblUsuariosMousePressed(evt);
            }
        });
        jLblUsuarios.setBounds(20, 40, 70, 17);
        jLayeredPaneSeguridad.add(jLblUsuarios, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel45.setFont(new java.awt.Font("Tahoma", 0, 18));
        jLabel45.setText("GESTIÓN DE ALMACENES");
        jLabel45.setBounds(140, 110, 229, 22);
        jLayeredPaneLogo.add(jLabel45, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel44.setFont(new java.awt.Font("Agency FB", 1, 36));
        jLabel44.setText("<html>Sistema<br>+Flow</html>");
        jLabel44.setBounds(150, 10, 180, 86);
        jLayeredPaneLogo.add(jLabel44, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel9.setBackground(new java.awt.Color(0, 0, 0));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/logoMasFlow.png"))); // NOI18N
        jLabel9.setBounds(10, 20, 130, 105);
        jLayeredPaneLogo.add(jLabel9, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18))
                            .addComponent(jLabel1)))
                    .addComponent(jLayeredPaneMantenimientos, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(jLayeredPaneProcesos, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(jLabel6))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(71, 71, 71)
                                .addComponent(jLabel2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLayeredPaneReportes, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLayeredPaneSeguridad, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel7))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(39, 39, 39)
                                        .addComponent(jLabel4)))
                                .addGap(55, 55, 55)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(jLabel3))
                                    .addComponent(jLabel8)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(jLayeredPaneLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)))
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLayeredPaneProcesos, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLayeredPaneSeguridad, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLayeredPaneReportes, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLayeredPaneLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLayeredPaneMantenimientos)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jLabel5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MousePressed
    // TODO add your handling code here:
}//GEN-LAST:event_jLabel5MousePressed

private void jLblRacksMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLblRacksMousePressed
    if(this.jLblRacks.isEnabled()){
    Mantenimientos.Rack.AdmRack a = new Mantenimientos.Rack.AdmRack();
    a.setVisible(true);// TODO add your handling code here:
    }
}//GEN-LAST:event_jLblRacksMousePressed

private void jLblIngresarProductosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLblIngresarProductosMousePressed
    if(this.jLblIngresarProductos.isEnabled()){
    Procesamiento.OrdenDeEntrega.AdmOrdenDeEntrega a = new Procesamiento.OrdenDeEntrega.AdmOrdenDeEntrega();
    a.setVisible(true);// TODO add your handling code here:
    }
}//GEN-LAST:event_jLblIngresarProductosMousePressed

private void jLblAlmacenesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLblAlmacenesMousePressed
    if(this.jLblAlmacenes.isEnabled()){
        Mantenimientos.Almacen.AdmAlmacen a = new Mantenimientos.Almacen.AdmAlmacen();
        a.setVisible(true);// TODO add your handling code here:
    }
}//GEN-LAST:event_jLblAlmacenesMousePressed

private void jLblZonasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLblZonasMousePressed
   if(this.jLblZonas.isEnabled()){
    Mantenimientos.Zona.AdmZona a = new Mantenimientos.Zona.AdmZona();
   a.setVisible(true);// TODO add your handling code here:
    }
}//GEN-LAST:event_jLblZonasMousePressed

private void jLblUbicacionesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLblUbicacionesMousePressed
   if(this.jLblUbicaciones.isEnabled()){
    Mantenimientos.Ubicacion.AdmUbicacion a = new Mantenimientos.Ubicacion.AdmUbicacion();
   a.setVisible(true);// TODO add your handling code here:
    }
}//GEN-LAST:event_jLblUbicacionesMousePressed

private void jLblFamiliaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLblFamiliaMousePressed
   if(this.jLblFamilia.isEnabled()){
    Mantenimientos.FamiliaProd.AdmFamiliaProd a = new Mantenimientos.FamiliaProd.AdmFamiliaProd();
   a.setVisible(true);// TODO add your handling code here:
    }
}//GEN-LAST:event_jLblFamiliaMousePressed

private void jLblProductosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLblProductosMousePressed
   if(this.jLblProductos.isEnabled()){
    Mantenimientos.Producto.AdmProducto a = new Mantenimientos.Producto.AdmProducto();
   a.setVisible(true);// TODO add your handling code here:
    }
}//GEN-LAST:event_jLblProductosMousePressed

private void jLblProveedoresMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLblProveedoresMousePressed
   if(this.jLblProveedores.isEnabled()){
    Mantenimientos.Proveedor.AdmProveedor a = new Mantenimientos.Proveedor.AdmProveedor();
   a.setVisible(true);// TODO add your handling code here:
    }
}//GEN-LAST:event_jLblProveedoresMousePressed

private void jLblClientesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLblClientesMousePressed
   if(this.jLblClientes.isEnabled()){
    Mantenimientos.Cliente.AdmCliente a = new Mantenimientos.Cliente.AdmCliente();
   a.setVisible(true);// TODO add your handling code here:
    }
}//GEN-LAST:event_jLblClientesMousePressed

private void jLblReporteStockMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLblReporteStockMousePressed
if(this.jLblReporteStock.isEnabled()){
    Reportes.Stock a = new Reportes.Stock();
   a.setVisible(true);// TODO add your handling code here:
    }
}//GEN-LAST:event_jLblReporteStockMousePressed

private void jLblKardekMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLblKardekMousePressed
if(this.jLblKardek.isEnabled()){
    Reportes.Kardex a = new Reportes.Kardex();
   a.setVisible(true);// TODO add your handling code here:
    }
}//GEN-LAST:event_jLblKardekMousePressed

private void jLblTrazabilidadPalletMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLblTrazabilidadPalletMousePressed
if(this.jLblTrazabilidadPallet.isEnabled()){
    Reportes.HistorialPallet a = new Reportes.HistorialPallet();
   a.setVisible(true);// TODO add your handling code here:
    }
}//GEN-LAST:event_jLblTrazabilidadPalletMousePressed

private void jLblPerfilesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLblPerfilesMousePressed
if(this.jLblPerfiles.isEnabled()){
    Seguridad.Perfil.AdmPerfil a = new Seguridad.Perfil.AdmPerfil();
   a.setVisible(true);// TODO add your handling code here:
    }
}//GEN-LAST:event_jLblPerfilesMousePressed

private void jLblCambioContrasenaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLblCambioContrasenaMousePressed

    if(this.jLblCambioContrasena.isEnabled()){
    Seguridad.CambiarContrasena a = new Seguridad.CambiarContrasena();
   a.setVisible(true);// TODO add your handling code here:
    }
}//GEN-LAST:event_jLblCambioContrasenaMousePressed

private void jLblLogAuditoriaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLblLogAuditoriaMousePressed
   if(this.jLblLogAuditoria.isEnabled()){
    Reportes.LogDeAuditoria a = new Reportes.LogDeAuditoria();
   a.setVisible(true);// TODO add your handling code here:
    }
}//GEN-LAST:event_jLblLogAuditoriaMousePressed

private void jLblDespacharProductosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLblDespacharProductosMousePressed
// TODO add your handling code here:
    if(this.jLblDespacharProductos.isEnabled()){
    Procesamiento.GuiaDeRemision.AdmGuiaDeRemision a = new Procesamiento.GuiaDeRemision.AdmGuiaDeRemision();
    a.setVisible(true);
    }
}//GEN-LAST:event_jLblDespacharProductosMousePressed

private void jLblMovimientosInternosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLblMovimientosInternosMouseClicked
    if(this.jLblMovimientosInternos.isEnabled()){
    Procesamiento.MovimientosInternos.AdmMovimientosInternos a = new Procesamiento.MovimientosInternos.AdmMovimientosInternos();
    a.setVisible(true);
    }
}//GEN-LAST:event_jLblMovimientosInternosMouseClicked

private void jLblUsuariosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLblUsuariosMousePressed
    // TODO add your handling code here:
    if(this.jLblUsuarios.isEnabled()){
    Seguridad.Usuario.AdmUsuario a = new Seguridad.Usuario.AdmUsuario();
   a.setVisible(true);// TODO add your handling code here:
    }

}//GEN-LAST:event_jLblUsuariosMousePressed

private void jLblLogUsuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLblLogUsuarioMousePressed
    // TODO add your handling code here:
       if(this.jLblLogUsuario.isEnabled()){
        Reportes.LogUsuario a = new Reportes.LogUsuario();
        a.setVisible(true);// TODO add your handling code here:
       }
}//GEN-LAST:event_jLblLogUsuarioMousePressed

private void jLabel10MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MousePressed
    Login L = new Login();
    L.setVisible(true);
    this.dispose();


    // TODO add your handling code here:
}//GEN-LAST:event_jLabel10MousePressed

private void jLblGuiaDeRemisionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLblGuiaDeRemisionMousePressed
    if(this.jLblGuiaDeRemision.isEnabled()){
        Reportes.GuiaDeRemision a = new Reportes.GuiaDeRemision();
        a.setVisible(true);
    }// TODO add your handling code here:
}//GEN-LAST:event_jLblGuiaDeRemisionMousePressed

private void jLblOrdenDeEntregaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLblOrdenDeEntregaMousePressed
        if(this.jLblOrdenDeEntrega.isEnabled()){
        Reportes.OrdenDeEntrega a = new Reportes.OrdenDeEntrega();
        a.setVisible(true);
    }// TODO add your handling code here:
}//GEN-LAST:event_jLblOrdenDeEntregaMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPaneLogo;
    private javax.swing.JLayeredPane jLayeredPaneMantenimientos;
    private javax.swing.JLayeredPane jLayeredPaneProcesos;
    private javax.swing.JLayeredPane jLayeredPaneReportes;
    private javax.swing.JLayeredPane jLayeredPaneSeguridad;
    private javax.swing.JLabel jLblAlmacenes;
    private javax.swing.JLabel jLblCambioContrasena;
    private javax.swing.JLabel jLblClientes;
    private javax.swing.JLabel jLblDespacharProductos;
    private javax.swing.JLabel jLblFamilia;
    private javax.swing.JLabel jLblGuiaDeRemision;
    private javax.swing.JLabel jLblIngresarProductos;
    private javax.swing.JLabel jLblKardek;
    private javax.swing.JLabel jLblLogAuditoria;
    private javax.swing.JLabel jLblLogUsuario;
    private javax.swing.JLabel jLblMovimientosInternos;
    private javax.swing.JLabel jLblOrdenDeEntrega;
    private javax.swing.JLabel jLblPerfiles;
    private javax.swing.JLabel jLblProductos;
    private javax.swing.JLabel jLblProveedores;
    private javax.swing.JLabel jLblRacks;
    private javax.swing.JLabel jLblReporteStock;
    private javax.swing.JLabel jLblTrazabilidadPallet;
    private javax.swing.JLabel jLblUbicaciones;
    private javax.swing.JLabel jLblUsuarios;
    private javax.swing.JLabel jLblZonas;
    // End of variables declaration//GEN-END:variables
}
