/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MantenimientoAlmacen.java
 *
 * Created on Oct 2, 2011, 2:57:54 PM
 */
package Mantenimientos.Almacen;
import BusinessEntity.AlmacenBE;
import BusinessLogic.AlmacenBL;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import BusinessEntity.DepartamentoBE;
import DataAccess.DepartamentoDA;
import BusinessEntity.ProvinciaBE;
import DataAccess.ProvinciaDA;
import BusinessEntity.DistritoBE;
import DataAccess.DistritoDA;
/**
 *
 * @author DIEGO
 */
public class MantenimientoAlmacen extends javax.swing.JFrame {

    /** Creates new form MantenimientoAlmacen */
    private AdmAlmacen objPadre;
    private String accion;
    private String codigo;
    private ArrayList<DepartamentoBE> departamentos= new ArrayList<DepartamentoBE>();
    private ArrayList<ProvinciaBE> provincias= new ArrayList<ProvinciaBE>();
    private ArrayList<DistritoBE> distritos= new ArrayList<DistritoBE>();

     public MantenimientoAlmacen(AdmAlmacen padre) {
        this.objPadre = padre;
        accion = "registrar";

        initComponents();
        this.setLocationRelativeTo(null);
        /*this.llenarComboDepartamentos();*/
        this.setTitle("+Flow - Registrar almacén");
        this.cbxActivo.setEnabled(false);
        this.setVisible(true);
    }

     public MantenimientoAlmacen(AdmAlmacen padre,AlmacenBE almacen){

        this.objPadre = padre;
        this.codigo=almacen.getIdAlmacen();
        accion = "modificar";

        initComponents();
        this.setLocationRelativeTo(null);
        this.setLocationRelativeTo(null);
        this.cbxActivo.setEnabled(true);
        this.cbxActivo.setSelected(true);
        this.setTitle("+Flow - Editar almacén");

        txtCodigo.setText(almacen.getIdAlmacen());
        txtNombre.setText(almacen.getNombre());
        txtDireccion.setText(almacen.getDireccion());
        txtTelefono.setText(almacen.getTelefono());
        txtLargo.setText(String.valueOf(almacen.getLargo()));
        txtAncho.setText(String.valueOf(almacen.getAncho()));

        /*this.llenarComboDepartamentos();
        DepartamentoBE departamento = DepartamentoDA.queryDepartamento(almacen.getIdDepartamento());
        cmbDepartamento.setSelectedItem(departamento.getDescripcion());
        this.llenarComboProvincias();
        ProvinciaBE provincia = ProvinciaDA.queryProvincia(almacen.getIdDepartamento(), almacen.getIdProvincia());
        cmbProvincia.setSelectedItem(provincia.getDescripcion());
        this.llenarComboDistritos();
        DistritoBE distrito = DistritoDA.queryDistrito(almacen.getIdDepartamento(), almacen.getIdProvincia(), almacen.getIdDistrito());
        cmbDistrito.setSelectedItem(distrito.getDescripcion());
        */
            if (almacen.getIndActivo().equals("1")){
                cbxActivo.setSelected(true);
            } else{
                cbxActivo.setSelected(false);
            }

            //txtIdDistrito.setText(cliente.getIdAlmacen());

            this.setVisible(true) ;


    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        txtLargo = new javax.swing.JTextField();
        txtAncho = new javax.swing.JTextField();
        cmbDistrito = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        txtTelefono = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        cbxActivo = new javax.swing.JCheckBox();
        cmbDepartamento = new javax.swing.JComboBox();
        cmbProvincia = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("+Flow - Registrar almacén");

        jLabel1.setText("Código:");

        jLabel2.setText("Largo*:");

        jLabel3.setText("Ancho*:");

        jLabel4.setText("Departamento:");

        jLabel5.setText("Provincia:");

        jLabel6.setText("Distrito:");

        txtCodigo.setEditable(false);

        jLabel7.setText("mts.");

        jLabel8.setText("mts.");

        btnGuardar.setText("Guardar");
        btnGuardar.setPreferredSize(new java.awt.Dimension(100, 23));
        btnGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnGuardarMousePressed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.setPreferredSize(new java.awt.Dimension(100, 23));
        btnCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnCancelarMousePressed(evt);
            }
        });
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jLabel9.setText("Dirección:");

        jLabel10.setText("Teléfono:");

        jLabel11.setText("Nombre*:");

        cbxActivo.setSelected(true);
        cbxActivo.setText("Activo");

        cmbDepartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbDepartamentoActionPerformed(evt);
            }
        });

        cmbProvincia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbProvinciaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel1)
                            .addComponent(jLabel11)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel9)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(4, 4, 4)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel2)
                                            .addComponent(cbxActivo))))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbProvincia, 0, 196, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtDireccion)
                                .addComponent(cmbDistrito, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                                .addComponent(txtTelefono))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtAncho, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtLargo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel7)))
                            .addComponent(cmbDepartamento, 0, 196, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cmbDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cmbProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cmbDistrito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtLargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtAncho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbxActivo)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
}//GEN-LAST:event_btnCancelarActionPerformed

private void btnCancelarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMousePressed
    this.dispose();    // TODO add your handling code here:
}//GEN-LAST:event_btnCancelarMousePressed

private void btnGuardarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMousePressed
     String indActivo = new String();
        if (cbxActivo.isSelected()) {indActivo="1";} else {indActivo="0";}



        AlmacenBL almacenBL = new AlmacenBL();
        try {
            if (this.accion.equals("registrar")){

                    almacenBL.insertar(txtCodigo.getText(),txtNombre.getText(),Double.parseDouble(txtLargo.getText()),
                    Double.parseDouble(txtAncho.getText()),txtDireccion.getText(),txtTelefono.getText(),
                    /*distritos.get(cmbDistrito.getSelectedIndex()).getIdDistrito(),
                    provincias.get(cmbProvincia.getSelectedIndex()).getIdProvincia(),
                    departamentos.get(cmbDepartamento.getSelectedIndex()).getIdDepartamento(), */ "","","", indActivo );
                    AlmacenBE almacen = almacenBL.getAlmacen();
                    this.objPadre.recargaruno(almacen);
                    this.dispose();
            } else {
                AlmacenBE almacen = new AlmacenBE(txtCodigo.getText(),txtNombre.getText(),Double.parseDouble(txtLargo.getText()),
                    Double.parseDouble(txtAncho.getText()),txtDireccion.getText(),txtTelefono.getText(),
                    /*distritos.get(cmbDistrito.getSelectedIndex()).getIdDistrito(),
                    provincias.get(cmbProvincia.getSelectedIndex()).getIdProvincia(),
                    departamentos.get(cmbDepartamento.getSelectedIndex()).getIdDepartamento(),*/"","","",  indActivo);

                    almacenBL.modificar(almacen);
                        int fila;
                        fila = this.objPadre.getDgvAlmacen().getSelectedRow();
                        this.objPadre.getDgvAlmacen().removeRowSelectionInterval(fila, fila);
                        
                        this.objPadre.getDgvAlmacen().setValueAt(almacen.getIdAlmacen(), fila, 0);
                        this.objPadre.getDgvAlmacen().setValueAt(almacen.getNombre(), fila, 1);
                        this.objPadre.getDgvAlmacen().setValueAt((String)cmbDistrito.getSelectedItem(), fila, 3);
                        this.objPadre.getDgvAlmacen().setValueAt((String)cmbProvincia.getSelectedItem(), fila, 4);
                        this.objPadre.getDgvAlmacen().setValueAt((String)cmbDepartamento.getSelectedItem(), fila, 5);
                        if(almacen.getIndActivo().equals("1")){
                             this.objPadre.getDgvAlmacen().setValueAt("Activo", fila, 2);
                         }else if(almacen.getIndActivo().equals("0")){
                            this.objPadre.getDgvAlmacen().setValueAt("Inactivo", fila, 2);
                         }
                        this.dispose();


                    }



        } catch (Exception ex) {
            Logger.getLogger(MantenimientoAlmacen.class.getName()).log(Level.SEVERE, null, ex);
        }

    // TODO add your handling code here:
}//GEN-LAST:event_btnGuardarMousePressed

private void cmbDepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbDepartamentoActionPerformed
    if (cmbDepartamento.getSelectedIndex()!=0){
        this.llenarComboProvincias();
    }// TODO add your handling code here:
}//GEN-LAST:event_cmbDepartamentoActionPerformed

private void cmbProvinciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbProvinciaActionPerformed
    if (cmbProvincia.getSelectedIndex()!=0){
        this.llenarComboDistritos();
    }// TODO add your handling code here:
}//GEN-LAST:event_cmbProvinciaActionPerformed

    /**
     * @param args the command line arguments
     */
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JCheckBox cbxActivo;
    private javax.swing.JComboBox cmbDepartamento;
    private javax.swing.JComboBox cmbDistrito;
    private javax.swing.JComboBox cmbProvincia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtAncho;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtLargo;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables

    private void llenarComboDepartamentos() {
       
        cmbDepartamento.removeAllItems();
        
        try {

           departamentos = DataAccess.DepartamentoDA.queryAllDepartamento();
        cmbDepartamento.addItem("Seleccione");
        for (DepartamentoBE Departamento : departamentos){
            cmbDepartamento.addItem((Departamento.getDescripcion()));
        }
} catch (Exception ex) {
            Logger.getLogger(MantenimientoAlmacen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void llenarComboProvincias() {
        
            if (distritos.size()>0)this.distritos.clear();
            if (provincias.size()>0)this.provincias.clear();
            this.cmbProvincia.removeAllItems();
            this.cmbDistrito.removeAllItems();
         try {   provincias = DataAccess.ProvinciaDA.queryAllProvincia(
                    departamentos.get(cmbDepartamento.getSelectedIndex()).getIdDepartamento());
        cmbProvincia.addItem("Seleccione");
        for (ProvinciaBE Provincia : provincias){
            cmbProvincia.addItem((Provincia.getDescripcion()));

        }
} catch (Exception ex) {
            Logger.getLogger(MantenimientoAlmacen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void llenarComboDistritos() {
        

             if (distritos.size()>0)this.distritos.clear();
             this.cmbDistrito.removeAllItems();
        try {    distritos = DataAccess.DistritoDA.queryAllDistrito(
                departamentos.get(cmbDepartamento.getSelectedIndex()).getIdDepartamento(),
                provincias.get(cmbProvincia.getSelectedIndex()).getIdProvincia());
        cmbDistrito.addItem("Seleccione");
        for (DistritoBE Distrito : distritos){
            cmbDistrito.addItem((Distrito.getDescripcion()));
        }
} catch (Exception ex) {
            Logger.getLogger(MantenimientoAlmacen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
