/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AdmProducto.java
 *
 * Created on Oct 2, 2011, 3:26:09 PM
 */
package Mantenimientos.Producto;

import BusinessEntity.ProductoBE;
import DataAccess.FamiliaDA;
import DataAccess.ProductoDA;
import DataAccess.UnidadMedidaDA;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DIEGO
 */
public class AdmProducto extends javax.swing.JFrame {

    private String idProducto;
    private boolean seleccionCliente = false;
    public ArrayList<ProductoBE> arrProductos;
    private FamiliaDA objFamiliaDA;
    private UnidadMedidaDA objUnidadMedidaDA;
    /** Creates new form AdmProducto */
    public AdmProducto() {
        initComponents();
        
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        dgvProductos = new javax.swing.JTable();
        jToolBar1 = new javax.swing.JToolBar();
        lblRegistrar = new javax.swing.JLabel();
        lblModificar = new javax.swing.JLabel();
        lblEliminar = new javax.swing.JLabel();
        lblBuscar = new javax.swing.JLabel();
        lblActualizar = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("+Flow - Administrar producto");

        dgvProductos.setAutoCreateRowSorter(true);
        dgvProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Código", "Nombre", "Descripción", "Familia", "Cant. Máx. por Pallet", "Unidad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Byte.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        dgvProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dgvProductosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(dgvProductos);
        dgvProductos.getColumnModel().getColumn(0).setPreferredWidth(40);
        dgvProductos.getColumnModel().getColumn(4).setPreferredWidth(30);
        dgvProductos.getColumnModel().getColumn(5).setPreferredWidth(30);

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        lblRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/add_page.png"))); // NOI18N
        lblRegistrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblRegistrarMousePressed(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRegistrarMouseClicked(evt);
            }
        });
        jToolBar1.add(lblRegistrar);
        lblRegistrar.getAccessibleContext().setAccessibleDescription("");

        lblModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/download.png"))); // NOI18N
        lblModificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblModificarMouseClicked(evt);
            }
        });
        jToolBar1.add(lblModificar);

        lblEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/delete_page.png"))); // NOI18N
        lblEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblEliminarMouseClicked(evt);
            }
        });
        jToolBar1.add(lblEliminar);

        lblBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/search_page.png"))); // NOI18N
        lblBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblBuscarMousePressed(evt);
            }
        });
        jToolBar1.add(lblBuscar);

        lblActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/refresh.png"))); // NOI18N
        jToolBar1.add(lblActualizar);

        jLabel7.setText("                                                                                                   ");
        jToolBar1.add(jLabel7);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/info.png"))); // NOI18N
        jToolBar1.add(jLabel6);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 601, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void lblRegistrarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegistrarMousePressed
//MantenimientoProducto m = new MantenimientoProducto();
//m.setVisible(true);
// TODO add your handling code here:
}//GEN-LAST:event_lblRegistrarMousePressed

    private void lblBuscarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBuscarMousePressed
       BuscarProducto b = new BuscarProducto(this);
       b.setVisible(true);
    }//GEN-LAST:event_lblBuscarMousePressed

    private void lblRegistrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegistrarMouseClicked
        MantenimientoProducto mantenimientoProducto = new MantenimientoProducto();
        mantenimientoProducto.setVisible(true);
    }//GEN-LAST:event_lblRegistrarMouseClicked

    private void lblModificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblModificarMouseClicked
        int fila;
        fila = dgvProductos.getSelectedRow();
        if (fila==-1)
            JOptionPane.showMessageDialog(null, "No ha seleccionado ninguna celda", "Error", 0);
        else{
            idProducto = (String)dgvProductos.getValueAt(fila, 0);
            MantenimientoProducto mantenimientoProducto = new MantenimientoProducto('M',idProducto);
            mantenimientoProducto.setVisible(true);
        }
    }//GEN-LAST:event_lblModificarMouseClicked

    private void lblEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEliminarMouseClicked
        int fila;
        fila = dgvProductos.getSelectedRow();
        if (fila==-1)
            JOptionPane.showMessageDialog(null, "No ha seleccionado ninguna celda", "Error", 0);
        else{
            idProducto = (String)dgvProductos.getValueAt(fila, 0);
            MantenimientoProducto mantenimientoProducto = new MantenimientoProducto('E',idProducto);
            mantenimientoProducto.setVisible(true);
        }
    }//GEN-LAST:event_lblEliminarMouseClicked

    private void dgvProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dgvProductosMouseClicked

    }//GEN-LAST:event_dgvProductosMouseClicked

    public void llenarDgv(ArrayList<ProductoBE> arrProductos){
        
        DefaultTableModel modelo=(DefaultTableModel) dgvProductos.getModel();    
        for(int i=modelo.getRowCount()-1; i>=0; i--){
            modelo.removeRow(i);
        }
        this.arrProductos = arrProductos;
        dgvProductos.clearSelection();
        objUnidadMedidaDA = new UnidadMedidaDA();                
        objFamiliaDA = new FamiliaDA();
        
        for (int i=0; i<arrProductos.size(); i++){
            
            String strIdProducto = arrProductos.get(i).getIdProducto();
            String strNombre = arrProductos.get(i).getNombre();
            String strDescripcion = arrProductos.get(i).getDescripcion();
            String strNombreFamilia = objFamiliaDA.queryByIdFamilia(arrProductos.get(i).getIdFamilia()).getNombre();
            String strNombreUnidad = objUnidadMedidaDA.queryByIdUnidadMedida(arrProductos.get(i).getIdUnidadMedida()).getNombre();
            
            modelo.addRow(new Object[]{strIdProducto,strNombre,strDescripcion,strNombreFamilia,strNombreUnidad});
            
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdmProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdmProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdmProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdmProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new AdmProducto().setVisible(true);
                
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable dgvProductos;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lblActualizar;
    private javax.swing.JLabel lblBuscar;
    private javax.swing.JLabel lblEliminar;
    private javax.swing.JLabel lblModificar;
    private javax.swing.JLabel lblRegistrar;
    // End of variables declaration//GEN-END:variables
}
