/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AdmPallet.java
 *
 * Created on Oct 2, 2011, 3:27:56 PM
 */
package Mantenimientos.Pallet;

import BusinessEntity.PalletBE;
import BusinessLogic.PalletBL;
import BusinessLogic.ProductoBL;
import BusinessLogic.RackBL;
import BusinessLogic.UbicacionBL;
import BusinessLogic.UnidadMedidaBL;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DIEGO
 */
public class AdmPallet extends javax.swing.JFrame {

    /** Creates new form AdmPallet */
    ArrayList<PalletBE> arrPallets;
    PalletBL objPalletBL;
    String strIdPallet;
    ProductoBL objProductoBL;
    UbicacionBL objUbicacionBL;
    RackBL objRackBL;
    String idPallet;
    
    public AdmPallet() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        dgvPallets = new javax.swing.JTable();
        jToolBar1 = new javax.swing.JToolBar();
        lblRegistrarPallet = new javax.swing.JLabel();
        lblEliminarPallet = new javax.swing.JLabel();
        lblBuscarPallet = new javax.swing.JLabel();
        lblRefrescarPallets = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("+Flow - Administrar pallet");

        dgvPallets.setAutoCreateRowSorter(true);
        dgvPallets.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Código", "Producto", "Rack", "Cant. Máx.", "Unidad", "Fecha Vencimiento"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Byte.class, java.lang.Object.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(dgvPallets);
        dgvPallets.getColumnModel().getColumn(0).setResizable(false);
        dgvPallets.getColumnModel().getColumn(0).setPreferredWidth(40);
        dgvPallets.getColumnModel().getColumn(1).setResizable(false);
        dgvPallets.getColumnModel().getColumn(1).setPreferredWidth(25);
        dgvPallets.getColumnModel().getColumn(2).setResizable(false);
        dgvPallets.getColumnModel().getColumn(3).setResizable(false);
        dgvPallets.getColumnModel().getColumn(3).setPreferredWidth(25);
        dgvPallets.getColumnModel().getColumn(4).setResizable(false);
        dgvPallets.getColumnModel().getColumn(5).setResizable(false);
        dgvPallets.getColumnModel().getColumn(5).setPreferredWidth(35);

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        lblRegistrarPallet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/add_page.png"))); // NOI18N
        lblRegistrarPallet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRegistrarPalletMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblRegistrarPalletMousePressed(evt);
            }
        });
        jToolBar1.add(lblRegistrarPallet);

        lblEliminarPallet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/delete_page.png"))); // NOI18N
        lblEliminarPallet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblEliminarPalletMouseClicked(evt);
            }
        });
        jToolBar1.add(lblEliminarPallet);

        lblBuscarPallet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/search_page.png"))); // NOI18N
        lblBuscarPallet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblBuscarPalletMousePressed(evt);
            }
        });
        jToolBar1.add(lblBuscarPallet);

        lblRefrescarPallets.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/refresh.png"))); // NOI18N
        lblRefrescarPallets.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRefrescarPalletsMouseClicked(evt);
            }
        });
        jToolBar1.add(lblRefrescarPallets);

        jLabel7.setText("                                                                                                   ");
        jToolBar1.add(jLabel7);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/info.png"))); // NOI18N
        jToolBar1.add(jLabel6);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void lblRegistrarPalletMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegistrarPalletMousePressed

}//GEN-LAST:event_lblRegistrarPalletMousePressed

    private void lblBuscarPalletMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBuscarPalletMousePressed
        BuscarPallet ventana = new BuscarPallet(this);
        ventana.setVisible(true);
    }//GEN-LAST:event_lblBuscarPalletMousePressed

private void lblRegistrarPalletMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegistrarPalletMouseClicked
    MantenimientoPallet ventana = new MantenimientoPallet(this);
    ventana.setVisible(true);
}//GEN-LAST:event_lblRegistrarPalletMouseClicked

private void lblEliminarPalletMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEliminarPalletMouseClicked
    int fila;
    fila = dgvPallets.getSelectedRow();
    if (fila==-1)
        JOptionPane.showMessageDialog(null, "No ha seleccionado ninguna celda", "Error", 0);
    else{
        if (JOptionPane.showConfirmDialog(null, "La eliminación será permanente, ¿realmente desea realizar la acción?") == 0){
            idPallet = (String)dgvPallets.getValueAt(fila, 0);
            PalletBL objPalletBL = new PalletBL();
            objPalletBL.eliminar(idPallet);
            eliminaFilaDgv(fila);
        }
    }
}//GEN-LAST:event_lblEliminarPalletMouseClicked

private void lblRefrescarPalletsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRefrescarPalletsMouseClicked
    objPalletBL = new PalletBL();
    llenarDgv(objPalletBL.getAll());
}//GEN-LAST:event_lblRefrescarPalletsMouseClicked

    public void llenarDgv(ArrayList<PalletBE> arrPallets){
        
        DefaultTableModel modelo=(DefaultTableModel) dgvPallets.getModel();    
        limpiarDgv();
        this.arrPallets = arrPallets;
        dgvPallets.clearSelection();
        objProductoBL = new ProductoBL();                
        objUbicacionBL = new UbicacionBL();
        objRackBL = new RackBL();
        String strNombreProducto = "";
        int intMaxCantPallet = 0;
        int intFila = 0;
        int intColumna = 0;
        String strIdentificadorRack = "";
        
        for (int i=0; i<arrPallets.size(); i++){
            
            strIdPallet = arrPallets.get(i).getIdPallet();
            
            String strIdProducto = arrPallets.get(i).getIdProducto().trim();
        
             if (!strIdProducto.equals("")){
                strNombreProducto = objProductoBL.getByIdProducto(arrPallets.get(i).getIdProducto()).getNombre();
                intMaxCantPallet = objProductoBL.getByIdProducto(arrPallets.get(i).getIdProducto()).getMaxCantPorPallet();
            }
            
            String strIdUbicacion = arrPallets.get(i).getIdUbicacion().trim();
            
            if (!strIdUbicacion.equals("")){
                intFila = objUbicacionBL.getUbicacionById(strIdUbicacion).getFila();
                intColumna = objUbicacionBL.getUbicacionById(strIdUbicacion).getColumna();
                strIdentificadorRack = objRackBL.getRackByIdUbicacion(strIdUbicacion).getIdentificador();
            }
            
            modelo.addRow(new Object[]{strIdPallet,strNombreProducto,strIdentificadorRack,intMaxCantPallet,intFila,intColumna});
            
        }
    }
    
    public void limpiarDgv(){
                
        DefaultTableModel modelo=(DefaultTableModel) dgvPallets.getModel();    
        for(int i=modelo.getRowCount()-1; i>=0; i--){
            modelo.removeRow(i);
        }
    }
    
    public void eliminaFilaDgv(int fila){
        DefaultTableModel modelo=(DefaultTableModel) dgvPallets.getModel();  
        modelo.removeRow(fila);
    }
    
    
    public void actualizaDgv(PalletBE palletBE){

       DefaultTableModel modelo=(DefaultTableModel) dgvPallets.getModel();    
        for(int i=modelo.getRowCount()-1; i>=0; i--){
            modelo.removeRow(i);
        }
        dgvPallets.clearSelection();
        objProductoBL = new ProductoBL();                
        objUbicacionBL = new UbicacionBL();
        objRackBL = new RackBL();
        UnidadMedidaBL objUnidadMedidaBL = new UnidadMedidaBL();
        String strNombreProducto = "";
        int intMaxCantPallet = 0;
        int intFila = 0;
        int intColumna = 0;
        String strIdentificadorRack = "";
        String strIdUnidad = "";
        String fecha = "";
        strIdPallet = palletBE.getIdPallet();
        String strNombreUnidad = "";
        
        String strIdProducto = palletBE.getIdProducto().trim();
        
        if (!strIdProducto.equals("")){
            strNombreProducto = objProductoBL.getByIdProducto(strIdProducto).getNombre();
            intMaxCantPallet = objProductoBL.getByIdProducto(strIdProducto).getMaxCantPorPallet();
            strIdUnidad = objProductoBL.getByIdProducto(strIdProducto).getIdUnidadMedida();
            strNombreUnidad = objUnidadMedidaBL.getUnidadMedida(strIdUnidad).getNombre();
            
        }

        String strIdUbicacion = palletBE.getIdUbicacion().trim();

        if (!strIdUbicacion.equals("")){
            intFila = objUbicacionBL.getUbicacionById(strIdUbicacion).getFila();
            intColumna = objUbicacionBL.getUbicacionById(strIdUbicacion).getColumna();
            strIdentificadorRack = objRackBL.getRackByIdUbicacion(strIdUbicacion).getIdentificador();
        }
        
        if (palletBE.getFechaVencimiento() != null)
            fecha = palletBE.getFechaVencimiento().toString();
       
        modelo.addRow(new Object[]{strIdPallet,strNombreProducto,strIdentificadorRack, intMaxCantPallet,strNombreUnidad,fecha});


}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdmPallet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdmPallet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdmPallet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdmPallet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new AdmPallet().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable dgvPallets;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lblBuscarPallet;
    private javax.swing.JLabel lblEliminarPallet;
    private javax.swing.JLabel lblRefrescarPallets;
    private javax.swing.JLabel lblRegistrarPallet;
    // End of variables declaration//GEN-END:variables
}
