/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * VisualizarPallets.java
 *
 * Created on Nov 10, 2011, 3:20:48 AM
 */
package Procesamiento.OrdenDeEntrega;

import BusinessEntity.PalletBE;
import BusinessEntity.ProductoBE;
import BusinessEntity.UbicacionBE;
import BusinessEntity.UnidadMedidaBE;
import BusinessLogic.ProductoBL;
import BusinessLogic.UbicacionBL;
import BusinessLogic.UnidadMedidaBL;
import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;

/**
 *
 * @author DIEGO
 */
public class VisualizarPallets extends javax.swing.JFrame {
    private AdmOrdenDeEntrega padre;
    /** Creates new form VisualizarPallets */
    public VisualizarPallets(AdmOrdenDeEntrega objPadre,ArrayList<PalletBE> arrPallet) {
        this.padre = objPadre;
        initComponents();
        this.setLocationRelativeTo(null); 
        this.recargar(arrPallet);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblPallets = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("+Flow - Visualizar Pallets");

        tblPallets.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "IdOrdenEntrega", "NombreProducto", "IdUbicacion", "FechaVencimiento", "MaxCantPorPallet", "Unidad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblPallets);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 662, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(VisualizarPallets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(VisualizarPallets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(VisualizarPallets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(VisualizarPallets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//
//            public void run() {
//                new VisualizarPallets().setVisible(true);
//            }
//        });
//    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPallets;
    // End of variables declaration//GEN-END:variables
   
    public final void recargar(ArrayList<PalletBE> arrPallet){
    ////
         
        DefaultTableModel modelo= new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return false;  
            }
        };
        tblPallets.setModel(modelo);
        modelo.addColumn("IdOrdenEntrega");
        modelo.addColumn("NombreProducto");
        modelo.addColumn("IdUbicacion");
        modelo.addColumn("FechaVencimiento");
         modelo.addColumn("MaxCantPorPallet");
          modelo.addColumn("Unidad");
        
//        tblGuiaRemision.getColumnModel().getColumn(0).setPreferredWidth(40);
//        tblGuiaRemision.getColumnModel().getColumn(1).setPreferredWidth(100);
//        tblGuiaRemision.getColumnModel().getColumn(2).setPreferredWidth(120);
//        tblGuiaRemision.getColumnModel().getColumn(3).setPreferredWidth(40);
        
        for(int i = 0;i<arrPallet.size();i++){
            modelo.addRow(new Object[6]);
            
            tblPallets.setValueAt(arrPallet.get(i).getIdNotaIngreso(),i,0 );
            ProductoBL objProductoBL = new ProductoBL();
             ProductoBE objProductoBE = objProductoBL.getByIdProducto(arrPallet.get(i).getIdProducto());
            
            tblPallets.setValueAt(objProductoBE.getNombre(),i,1 );
            
            UbicacionBL objUbicacionBL = new UbicacionBL();
            UbicacionBE objUbicacionBE = objUbicacionBL.getUbicacionById(arrPallet.get(i).getIdUbicacion());
            String identificador = "F" + objUbicacionBE.getFila() + "C" + objUbicacionBE.getColumna();
            tblPallets.setValueAt(identificador,i,2 );
             tblPallets.setValueAt(arrPallet.get(i).getFechaVencimiento(),i,3 );
            tblPallets.setValueAt(objProductoBE.getMaxCantPorPallet(),i,4 );
            UnidadMedidaBL objUnidadMedidaBL = new UnidadMedidaBL();
            UnidadMedidaBE objUnidadMedidaBE = objUnidadMedidaBL.getUnidadMedida(arrPallet.get(i).getIdProducto());
            tblPallets.setValueAt(objUnidadMedidaBE.getNombre(),i,5 );
        }
        
    }
    
   
}
