/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * GUIMapa.java
 *
 * Created on 02/11/2011, 07:18:04 PM
 */

package Algoritmos.Mapa;

import Algoritmos.RecorridoOptimo.Cromosoma;
import BusinessEntity.UbicacionBE;
import Util.Configuracion;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.util.ArrayList;
import javax.swing.JPanel;

/**
 *
 * @author carlitos
 */
public class GUIMapa extends javax.swing.JFrame {

    /** Creates new form GUIMapa */
    public GUIMapa() {
        initComponents();
    }

    public GUIMapa(Mapa mapa) {
        this.mapa = mapa;
        calcularFactores();
        initComponents();
    }

    public GUIMapa(Mapa mapa, ArrayList<UbicacionBE> mejoresUbicaciones) {
        this.mapa = mapa;
        calcularFactores();
        this.mejoresUbicaciones= mejoresUbicaciones;
        initComponents();        
    }
        
    public GUIMapa(Mapa mapa, Cromosoma mejorCromosoma) {
        this.mapa = mapa;
        calcularFactores();
        this.mejorCromosoma = mejorCromosoma;
        initComponents();
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setTitle("Mapa del almacén");
        setBounds(new java.awt.Rectangle(400, 400, 800, 600));
        setName("mapaFrame"); // NOI18N
        getContentPane().setLayout(null);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIMapa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables


    @Override
    public void paint(Graphics g) {

           Graphics2D g2 = (Graphics2D)g;
           g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING,
                 RenderingHints.VALUE_ANTIALIAS_ON);
           g2.setRenderingHint(RenderingHints.KEY_INTERPOLATION,RenderingHints.VALUE_INTERPOLATION_BICUBIC);

           super.paint(g);

           dibujaUbicaciones(g);
           
    }


    private void dibujaUbicaciones(Graphics g)
    {
        for (Nodo nodo : mapa.getListaNodos())
        {
            if (nodo.isNodoInicial())
            {
                g.setColor(Color.YELLOW);
                g.drawRect(convertirX(nodo.getX())+20, convertirY(nodo.getY())+20,factorX, factorY);
            }
            else if (nodo.getItem()==null)
            {
                g.setColor(Color.BLACK);
                g.drawRect(convertirX(nodo.getX())+20, convertirY(nodo.getY())+20, factorX, factorY);
            }
            else
            {
                g.setColor(Color.RED);
                g.drawRect(convertirX(nodo.getX())+20, convertirY(nodo.getY())+20, factorX, factorY);
            }
        }
    }


    private void calcularFactores()
    {
        factorX = pixelesLargo/mapa.getNumX();
        factorY = pixelesAncho/mapa.getNumY();
    }

    private int convertirX(int x)
    {
        return x*factorX;
    }

    private int convertirY(int y)
    {
        return y*factorY;
    }


    private Mapa mapa;
    private ArrayList<UbicacionBE> mejoresUbicaciones;
    private Cromosoma mejorCromosoma;

    private int pixelesLargo=1024;
    private int pixelesAncho=768;

    private int factorX;
    private int factorY;

}
